ALTER TABLE Personen
ADD FOREIGN KEY (Vorname_Nr)
REFERENCES Vornamen (Nummer)
ON DELETE CASCADE;

ALTER TABLE Personen
ADD FOREIGN KEY (Familie_Nr)
REFERENCES Familien (Nummer)
ON DELETE CASCADE;

ALTER TABLE Personen
ADD FOREIGN KEY (Mutter_Nr)
REFERENCES Personen (Nummer)
ON DELETE CASCADE;

ALTER TABLE Personen
ADD FOREIGN KEY (Vater_Nr)
REFERENCES Personen (Nummer)
ON DELETE CASCADE;

ALTER TABLE Personen
ADD FOREIGN KEY (Partner_Nr)
REFERENCES Personen (Nummer)
ON DELETE CASCADE;
